import os

APP_TITLE = "SQL + LLM Company Chatbot"
DB_DIR = "data"
DB_PATH = os.path.join(DB_DIR, "company.db")
TABLES = ["company", "departments", "employees", "products", "policies", "papers"]
DB_SIZE_VALUES = ["small", "medium", "large"]

MAX_SQL_ROWS = 200
MAX_LLM_ROWS = 200

SCHEMA_TOPK_TABLES = 3
SCHEMA_TOPK_COLUMNS = 12
SQL_RETRY_ON_EMPTY = True
SQL_RETRY_ON_ERROR = True
ENABLE_EXAMPLES_IN_PROMPT = True

MODEL_OPTIONS = ["gpt-4o-mini", "gpt-4o", "gpt-4.1-mini", "gpt-4.1", "gpt-3.5-turbo"]

PAPER_COUNT_PRESETS = {
    "small": 8,
    "medium": 15,
    "large": 25,
}


TEXT = {
    "en": {
        "title": "Talking Potatoes",
        "subtitle": "Create a virtual company database with an LLM, then chat over it using SQL.",
        "tab_setup": "Setup",
        "tab_db": "DB Status",
        "tab_chat": "Chatbot",
        "lang_toggle": "한국어로 전환",
        "lang_label": "Language",
        "api_section": "LLM Settings",
        "api_key": "OpenAI API Key",
        "api_key_help": "Stored only in session state. Required to call the LLM.",
        "model": "Model",
        "model_help": "Choose a model for generation and chat.",
        "chat_system_prompt_label": "Chatbot system prompt",
        "chat_system_prompt_help": "Optional. You can use {guardrails}, {language}, {examples} placeholders.",
        "base_url": "Base URL (optional)",
        "base_url_help": "Use this to point to a compatible API endpoint.",
        "company_section": "Company Seed",
        "prompt_section": "Generation Prompts",
        "system_prompt_label": "Generation system prompt",
        "user_prompt_label": "Generation user prompt",
        "llm_response_label": "LLM response",
        "db_size": "DB size",
        "db_size_help": "Controls how much data the LLM generates.",
        "db_size_options": ["Small", "Medium", "Large"],
        "agent_section": "LLM Agent Draft",
        "agent_toggle": "Enable LLM agent drafting",
        "agent_model": "Agent model",
        "agent_intent": "Intent (what you want to ask)",
        "agent_generate": "Generate draft",
        "agent_draft": "Draft message",
        "agent_send": "Confirm and send",
        "agent_missing_intent": "Please enter your intent before generating.",
        "agent_empty_draft": "Draft is empty. Generate or write a message first.",
        "sql_debug_title": "SQL Execution",
        "sql_debug_query": "Executed SQL",
        "sql_debug_results": "SQL Results",
        "sql_debug_error": "SQL Error",
        "sql_debug_empty": "No rows returned.",
        "sql_debug_skipped": "SQL was not executed for this message.",
        "small_talk_response": "Hi! Ask me about the company database.",
        "no_sql_response": "I couldn't generate a database query for that. Please ask about the company data.",
        "no_data_response": "No matching data was found in the database.",
        "sql_error_response": "I couldn't run the database query. Please try again.",
        "company_name": "Company name (optional)",
        "industry": "Industry",
        "location": "HQ location",
        "size": "Approx. employee count",
        "tone": "Communication tone",
        "tone_options": ["Professional", "Friendly", "Formal", "Casual"],
        "generate": "Generate Company + Database",
        "overwrite_db": "Overwrite existing database",
        "db_created": "Database created successfully.",
        "db_exists": "Database already exists. Enable overwrite to regenerate.",
        "missing_key": "Please provide an API key to generate with the LLM.",
        "missing_sdk": "OpenAI SDK is not available. Install requirements first.",
        "llm_error": "LLM call failed. Check your API key and model.",
        "parse_error": "Could not parse LLM response as JSON. Try again.",
        "chat_ready": "Chat with your company assistant.",
        "no_db": "No database yet. Please generate one in the Setup tab.",
        "refresh_context": "Refresh DB context",
        "reset_chat": "Reset conversation",
        "user_input": "Ask about the company, people, products, or policies...",
        "context_updated": "DB context refreshed.",
        "db_status_title": "Database Overview",
        "db_status_counts": "Table row counts",
        "db_status_empty": "No rows available.",
        "db_path_label": "DB path",
        "research_section": "Research Dataset",
        "research_topic": "Research topic",
        "research_years": "Publication years",
        "research_count": "Number of papers",
        "research_count_help": "Used when generating papers with the LLM.",
        "generate_papers": "Generate Papers",
        "papers_created": "Papers dataset created successfully.",
        "missing_topic": "Please enter a research topic.",
        "research_prompt_section": "Research Prompts",
        "papers_response_label": "Papers LLM response",
    },
    "ko": {
        "title": "말하는 감자들",
        "subtitle": "LLM으로 가상 회사를 만들고 SQL로 읽어 대화하는 챗봇입니다.",
        "tab_setup": "설정",
        "tab_db": "DB 상태",
        "tab_chat": "챗봇",
        "lang_toggle": "Switch to English",
        "lang_label": "언어",
        "api_section": "LLM 설정",
        "api_key": "OpenAI API Key",
        "api_key_help": "세션에만 저장됩니다. LLM 호출에 필요합니다.",
        "model": "모델",
        "model_help": "생성과 챗봇에 사용할 모델을 선택하세요.",
        "chat_system_prompt_label": "챗봇 시스템 프롬프트",
        "chat_system_prompt_help": "선택 사항입니다. {guardrails}, {language}, {examples} 치환자를 사용할 수 있습니다.",
        "base_url": "Base URL (선택)",
        "base_url_help": "호환 API 엔드포인트를 사용할 때 입력하세요.",
        "company_section": "회사 기본 정보",
        "prompt_section": "생성 프롬프트",
        "system_prompt_label": "생성 시스템 프롬프트",
        "user_prompt_label": "생성 유저 프롬프트",
        "llm_response_label": "LLM 응답",
        "db_size": "DB 크기",
        "db_size_help": "LLM이 생성하는 데이터 양을 조절합니다.",
        "db_size_options": ["작게", "보통", "크게"],
        "agent_section": "LLM 에이전트 초안",
        "agent_toggle": "LLM 에이전트로 메시지 초안 생성",
        "agent_model": "에이전트 모델",
        "agent_intent": "의도(무엇을 물어보고 싶은가요)",
        "agent_generate": "초안 생성",
        "agent_draft": "메시지 초안",
        "agent_send": "확인 후 전송",
        "agent_missing_intent": "초안을 생성하려면 의도를 입력하세요.",
        "agent_empty_draft": "초안이 비어있습니다. 생성하거나 직접 작성하세요.",
        "sql_debug_title": "SQL 실행",
        "sql_debug_query": "실행된 SQL",
        "sql_debug_results": "SQL 결과",
        "sql_debug_error": "SQL 오류",
        "sql_debug_empty": "반환된 데이터가 없습니다.",
        "sql_debug_skipped": "이 메시지는 SQL을 실행하지 않았습니다.",
        "small_talk_response": "안녕하세요! 회사 데이터에 대해 질문해 주세요.",
        "no_sql_response": "해당 질문에 대한 DB 쿼리를 만들 수 없었습니다. 회사 데이터에 대해 질문해 주세요.",
        "no_data_response": "DB에서 일치하는 데이터를 찾지 못했습니다.",
        "sql_error_response": "DB 쿼리를 실행하지 못했습니다. 다시 시도해 주세요.",
        "company_name": "회사명 (선택)",
        "industry": "산업",
        "location": "본사 위치",
        "size": "직원 수(대략)",
        "tone": "커뮤니케이션 톤",
        "tone_options": ["프로페셔널", "친근함", "격식", "캐주얼"],
        "generate": "회사 + 데이터베이스 생성",
        "overwrite_db": "기존 DB 덮어쓰기",
        "db_created": "데이터베이스가 생성되었습니다.",
        "db_exists": "이미 DB가 있습니다. 덮어쓰기를 체크하세요.",
        "missing_key": "LLM 생성을 위해 API Key를 입력하세요.",
        "missing_sdk": "OpenAI SDK를 사용할 수 없습니다. requirements를 설치하세요.",
        "llm_error": "LLM 호출에 실패했습니다. API Key와 모델을 확인하세요.",
        "parse_error": "LLM 응답을 JSON으로 해석하지 못했습니다. 다시 시도하세요.",
        "chat_ready": "회사 어시스턴트와 대화하세요.",
        "no_db": "DB가 없습니다. 설정 탭에서 먼저 생성하세요.",
        "refresh_context": "DB 컨텍스트 새로고침",
        "reset_chat": "대화 초기화",
        "user_input": "회사, 사람, 제품, 정책에 대해 물어보세요...",
        "context_updated": "DB 컨텍스트가 업데이트되었습니다.",
        "db_status_title": "데이터베이스 현황",
        "db_status_counts": "테이블 행 개수",
        "db_status_empty": "데이터가 없습니다.",
        "db_path_label": "DB 경로",
        "research_section": "연구 데이터",
        "research_topic": "연구 주제",
        "research_years": "발행 연도 범위",
        "research_count": "논문 수",
        "research_count_help": "LLM이 생성할 논문 수입니다.",
        "generate_papers": "논문 생성",
        "papers_created": "논문 데이터셋이 생성되었습니다.",
        "missing_topic": "연구 주제를 입력하세요.",
        "research_prompt_section": "연구 프롬프트",
        "papers_response_label": "논문 LLM 응답",
    },
}
